export const TIMELINE_COLUMNS = [
  'SCAN',
  'ROAM',
  'DISCONNECT',
  'CONNECT',
  'DHCP',
  'RSSI_CHANGE',
  'LINK_SPEED_CHANGE',
  'VALIDATION',
  'CAPTIVE_PORTAL',
  'WIFI_ON',
  'WIFI_OFF',
  'WIFI_IFACE_UP',
  'WIFI_IFACE_DOWN',
  'DOZE_ENTER',
  'DOZE_EXIT',
  'IDLE_ENTER',
  'IDLE_EXIT',
  'BATTERY_SAVER_ON',
  'BATTERY_SAVER_OFF',
  'ALARM_QUEUE_JUMP',
  'ALARM_WAKEUP_BURST',
  'ALARM_WAKEUP_SOON',
  'JOB_ACTIVE_SPIKE',
  'WAKELOCK_SPIKE'
];

export const NETWORK_EVENT_TYPES = [
  'SCAN',
  'ROAM',
  'DISCONNECT',
  'CONNECT',
  'DHCP',
  'RSSI_CHANGE',
  'LINK_SPEED_CHANGE',
  'VALIDATION',
  'CAPTIVE_PORTAL',
  'WIFI_ON',
  'WIFI_OFF',
  'WIFI_IFACE_UP',
  'WIFI_IFACE_DOWN'
];

export const INTERVAL_EVENT_TYPES = ['SCAN', 'ROAM', 'VALIDATION', 'DOZE_ENTER', 'ALARM_WAKEUP_BURST', 'ALARM_QUEUE_JUMP'];
export const PERIOD_TARGETS_SEC = [120, 300, 600, 900];
export const TOP_CANDIDATES = ['SCAN', 'VALIDATION', 'DOZE_ENTER', 'IDLE_ENTER', 'ROAM', 'ALARM_WAKEUP_BURST', 'ALARM_QUEUE_JUMP'];
export const TRANSITION_TYPES = ['DOZE_ENTER', 'DOZE_EXIT', 'IDLE_ENTER', 'IDLE_EXIT'];
